services:
  rmvision-core:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDPLATFORM=linux/arm64
    image: kielas_rmvision:latest
    container_name: rmvision-core
    network_mode: host
    privileged: true
    devices:
      - "/dev/video0:/dev/video0"
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/root/.Xauthority
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.Xauthority:/root/.Xauthority:rw
    working_dir: /ros_ws
    command: >
      bash -c "source /opt/ros/humble/setup.bash &&
               source /ros_ws/install/setup.bash &&
               ros2 launch rm_vision_bringup mv_nav.launch.py"